import { z } from "zod";
// Explicit .ts extension (unlike other local imports in this codebase) so
// scripts/generate-schema.ts can resolve this under plain Node, which -
// unlike Vite/Vitest - doesn't infer extensions for relative specifiers.
import { tokenizeKeys } from "./keys.ts";

export const localizedTextSchema = z.object({
	en: z.string().min(1),
	ja: z.string().min(1).optional(),
});
export type LocalizedText = z.infer<typeof localizedTextSchema>;

const initialStateSchema = z.object({
	text: z.string(),
	cursor: z.number().int().min(0),
	mode: z.literal("normal"),
});

const expectedStateSchema = z.object({
	text: z.string(),
	cursor: z.number().int().min(0).optional(),
	mode: z.enum(["normal", "insert"]).optional(),
	yankRegister: z.string().optional(),
});

const constraintsSchema = z.object({
	timeLimitSec: z.number().positive(),
	allowedOperators: z.array(z.string()).optional(),
	allowedMotions: z.array(z.string()).optional(),
	maxKeys: z.number().int().positive().optional(),
	requireInsertMode: z.boolean().optional(),
});

// examples[0] is required (not just documented as such): it is the reference
// solution used both by CI validation and to derive idealKeyCount.
export const challengeSchema = z.object({
	id: z.string().min(1),
	title: localizedTextSchema,
	prompt: localizedTextSchema,
	initial: initialStateSchema,
	expected: expectedStateSchema,
	constraints: constraintsSchema.optional(),
	hints: z.array(localizedTextSchema).optional(),
	examples: z.array(z.string()).min(1),
	tags: z.array(z.string()),
	difficulty: z.union([
		z.literal(1),
		z.literal(2),
		z.literal(3),
		z.literal(4),
		z.literal(5),
	]),
});
export type Challenge = z.infer<typeof challengeSchema>;

// Not stored as a field to avoid double bookkeeping - always derived from the
// reference solution's key count. Counted in tokens (see keys.ts), so
// "<Esc>" counts as one key, not five.
export function idealKeyCount(challenge: Challenge): number {
	return tokenizeKeys(challenge.examples[0]).length;
}

export type LoadedChallenge = { challenge: Challenge; file: string };

// import.meta.glob must stay inside a function body (not at module top
// level) so this file can still be imported by plain Node (e.g. the JSON
// Schema generation script) without Vite's transform - see scripts/generate-schema.ts.
export function loadChallenges(): LoadedChallenge[] {
	// schema.json (generated by scripts/generate-schema.ts) is not a challenge.
	const modules = import.meta.glob(
		["../../challenges/*.json", "!../../challenges/schema.json"],
		{
			eager: true,
		},
	) as Record<string, { default: unknown }>;

	const loaded = Object.entries(modules).map(([file, mod]) => {
		const result = challengeSchema.safeParse(mod.default);
		if (!result.success) {
			throw new Error(
				`Invalid challenge JSON at ${file}: ${result.error.message}`,
			);
		}
		return { challenge: result.data, file };
	});

	const seenIds = new Map<string, string>();
	for (const { challenge, file } of loaded) {
		const previousFile = seenIds.get(challenge.id);
		if (previousFile) {
			throw new Error(
				`Duplicate challenge id "${challenge.id}" in ${file} and ${previousFile}`,
			);
		}
		seenIds.set(challenge.id, file);
	}

	return loaded.sort((a, b) => a.challenge.id.localeCompare(b.challenge.id));
}
